language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=pypy-django18
  - TOXENV=pypy-django19
  - TOXENV=pypy-django110

after_success:
  - coveralls